# Generated by Django 5.0.4 on 2024-04-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='Student_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='Studnet_Pic'),
        ),
    ]
